### ISSUE TITLE
Модели  ruBert не скачиваются на Hugginface

### ISSUE THREAD

**Issue by DimIsaev** [sberbank-ai/model-zoo#2]
ruBert

Large: [HF Model](https://huggingface.co/sberbank-ai/ruBert-large)
Base: [HF Model](https://huggingface.co/sberbank-ai/ruBert-base)

![image](https://user-images.githubusercontent.com/11172642/167284898-e55933b3-90b1-4491-8e0d-e033c9dd2ac9.png)

**Comment by TatianaShavrina** [comment]
Hi @DimIsaev !
Thank you for reaching out! Do you have any thoughts, why is this happening?
I've just tried the example [colab](https://colab.research.google.com/github/sberbank-ai/model-zoo/blob/master/examples/Sber_ai_examples.ipynb) from this repo, and ruBert successfully downloaded and both models worked
Maybe smth with the download counter?

**Comment by TatianaShavrina** [comment]
Oh, I see, that is what the error message literally says, it cannot determine the pipeline type.

While the example code works as usual, I will dive in and explore how to fix this.

**Comment by TatianaShavrina** [comment]
Fixed
